source 'https://rubygems.org'

gem 'jekyll', '~> 3.6.3'
gem 'jekyll-assets', '~> 2.0.0'
gem 'bourbon', '~>3'

# For markdown header cleanup
gem 'sanitize', '>= 6.0.2'

gem 'wdm', '~> 0.1.0' if Gem.win_platform?
