source 'https://rubygems.org'

gem 'jekyll', '~>1.5.1'
gem 'jekyll-assets', '~> 2.2.1'
gem 'bourbon', '~>3'

# For markdown header cleanup
gem 'sanitize', '>= 4.5.0'

gem 'wdm', '~> 0.1.0' if Gem.win_platform?
